format_version: "9"
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: android
trigger_map:
- push_branch: jacklubbs-repo-stored-2-yml
  pipeline: pipeline-runif
- pull_request_source_branch: '*'
  workflow: prepare-workflow
app:
  envs:
  - PROJECT_LOCATION: .
  - VARIANT: ""
  - GRADLEW_PATH: ./gradlew
  - MODULE: 
pipelines:
  pipeline-runif:
    stages:
    - stage-1: {}
    - stage-2: {}
stages:
  stage-1:
    workflows:
    - prepare-workflow: {}
  stage-2:
    workflows:
    - parallel-test1:
        run_if: '{{getenv "BITRISE_GIT_BRANCH" | eq "jacklubbs-repo-stored-2-yml"}}'
    - parallel-test2:
        run_if: '{{ getenv "MODULE" | eq "p_test2&3" }}'
workflows:
  parallel-test1:
    meta:
      bitrise.io:
        stack: linux-docker-android-20.04
        machine_type_id: elite
    description: |
      ## How to get a signed APK, correct

      This workflow contains the **Sign APK** step. To sign your APK all you have to do is to:

      1. Click on **Code Signing** tab
      1. Find the **ANDROID KEYSTORE FILE** section
      1. Click or drop your file on the upload file field
      1. Fill the displayed 3 input fields:
       1. **Keystore password**
       1. **Keystore alias**
       1. **Private key password**
      1. Click on **[Save metadata]** button

      That's it! From now on, **Sign APK** step will receive your uploaded files.

      ## To run this workflow

      If you want to run this workflow manually:

      1. Open the app's build list page
      2. Click on **[Start/Schedule a Build]** button
      3. Select **parallel-test1** in **Workflow** dropdown input
      4. Click **[Start Build]** button

      Or if you need this workflow to be started by a GIT event:

      1. Click on **Triggers** tab
      2. Setup your desired event (push/tag/pull) and select **parallel-test1** workflow
      3. Click on **[Done]** and then **[Save]** buttons

      The next change in your repository that matches any of your trigger map event will start **parallel-test1** workflow.
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@8.1: {}
  parallel-test2:
    meta:
      bitrise.io:
        stack: linux-docker-android-20.04
        machine_type_id: elite
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@8.1: {}
  parallel-test3:
    meta:
      bitrise.io:
        stack: linux-docker-android-20.04
        machine_type_id: elite
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@8.1: {}
    - deploy-to-bitrise-io@2:
        inputs:
        - is_enable_public_page: "false"
    envs:
    - workflow_trigger: go_test_module
  prepare-workflow:
    meta:
      bitrise.io:
        stack: linux-docker-android-20.04
        machine_type_id: elite
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@8.1: {}
    - script:
        title: Generate and set new version code
        inputs:
        - content: |-
            #!/bin/bash
            # Get the current date in YYYYMMDD format
            DATE=$(date +%Y%m%d)

            # Get the Bitrise build number 1
            BUILD_NUM=$BITRISE_BUILD_NUMBER

            # Combine the date and build number to form the new version code
            NEW_VERSION_CODE="${DATE}${BUILD_NUM}"

            # Use envman to add the environment variable so it's available for subsequent steps
            envman add --key NEW_VERSION_CODE --value "$NEW_VERSION_CODE"

            # Optional: echo the value for debug logging
            echo "New version code is: $NEW_VERSION_CODE"
  parallel-test4:
    meta:
      bitrise.io:
        stack: linux-docker-android-20.04
        machine_type_id: elite
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@8.1: {}
    - deploy-to-bitrise-io@2:
        inputs:
        - is_enable_public_page: "false"
    envs:
    - workflow_trigger: go_test_module
meta:
  bitrise.io:
    stack: linux-docker-android-20.04
    machine_type_id: elite-xl
